tinkering...

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,6 +16,54 @@ jobs:
       - run:
           name: Deploy Shared Resources via AWS CLI
           command: |
+            echo "Checking if stack exists ..."
+            1=us-west-2
+            2=ghc-workshop-shared-resources
+            if ! aws cloudformation describe-stacks --region $1 --stack-name $2 ; then
+            
+              echo -e "\nStack does not exist, creating ..."
+              aws cloudformation create-stack \
+                --region $1 \
+                --stack-name $2 \
+            
+              echo "Waiting for stack to be created ..."
+              aws cloudformation wait stack-create-complete \
+                --region $1 \
+                --stack-name $2 \
+            
+            else
+            
+              echo -e "\nStack exists, attempting update ..."
+            
+              set +e
+              update_output=$( aws cloudformation update-stack \
+                --region $1 \
+                --stack-name $2 2>&1)
+              status=$?
+              set -e
+            
+              echo "$update_output"
+            
+              if [ $status -ne 0 ] ; then
+            
+                # Don't fail for no-op update
+                if [[ $update_output == *"ValidationError"* && $update_output == *"No updates"* ]] ; then
+                  echo -e "\nFinished create/update - no updates to be performed"
+                  exit 0
+                else
+                  exit $status
+                fi
+            
+              fi
+            
+              echo "Waiting for stack update to complete ..."
+              aws cloudformation wait stack-update-complete \
+                --region $1 \
+                --stack-name $2 \
+            
+            fi
+            
+            echo "Finished create/update successfully!"
             #aws cloudformation deploy --stack-name ghc-workshop-shared-resources --template-file cfn/shared_resources.yml --capabilities CAPABILITY_NAMED_IAM --parameter-overrides WorkshopName="ghc-workshop" --region us-west-2
           no_output_timeout: 20m
       - run:
